In [22]:
import numpy as np

In [23]:
a = np.array([1,2,3])
print(a)
print(a.ndim) #returns no. of dimensions

[1 2 3]
1


In [24]:
a = np.array([[1,2],[3,4]])
print(a.ndim)

2


In [25]:
print(a.itemsize) #print size of item in bytes
print(a.dtype)

4
int32


In [26]:
a = np.array([[1,2],[3,4]], dtype=np.float64)
print(a)
print(a.itemsize)
print(a.dtype)

[[1. 2.]
 [3. 4.]]
8
float64


In [28]:
print(a.size) #this property gives no. of elements/itmes

4


In [29]:
print(a.shape)

(2, 2)


In [34]:
a2 = np.zeros((3,4), dtype=np.int32) #default dtype is np.float64
print(a2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [35]:
a3 = np.ones((2,3))
print(a3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
a4 = np.arange(1,10) #arange stands for array range
print(a4)
a4 = np.arange(1,20,2) #2 is steps
print(a4)

[1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [61]:
a5 = np.linspace(1,5,10) #gives linear sequence
print(a5)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [62]:
a6 = np.array([[1,2],[3,4],[5,6]])
print(a6)
print(a6.shape)
a6.reshape(2,3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a6.ravel() #revel() function is used to flatten array and it will return new array (won't affect the original one i.e. a6 here)

array([1, 2, 3, 4, 5, 6])

In [64]:
print(a6.min())
print(a6.max())
print(a6.sum())
print(a6.sum(axis=0))
print(a6.sum(axis=1))
np.sqrt(a6)
print(np.std(a6)) #standard deviation

1
6
21
[ 9 12]
[ 3  7 11]
1.707825127659933


In [75]:
x1 = np.array([[1,2,3],[4,5,6]])
x2 = np.array([[7,8,9],[10,11,12]])

print(x1+x2)
print(x2-x1)
print(x1*x2)
print(x2/x1)

[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]
[[ 7 16 27]
 [40 55 72]]
[[7.  4.  3. ]
 [2.5 2.2 2. ]]


In [80]:
a.dot(a3)

array([[3., 3., 3.],
       [7., 7., 7.]])