In [28]:
import numpy as np

In [29]:
# Slicing and Indexing
a = np.array([5,6,7])
print(a[0:2])
print(a[-1])

[5 6]
7


In [30]:
a2 = np.array([[5,6,7],[2,6,4],[11,15,78]])
print(a2)
print(a2[1,2])  #row 1 and column 2
print(a2[-1])
print(a2[-2,0:2])

[[ 5  6  7]
 [ 2  6  4]
 [11 15 78]]
4
[11 15 78]
[2 6]


In [31]:
print(a2[:,1:3]) # only : will consider all rows

[[ 6  7]
 [ 6  4]
 [15 78]]


In [33]:
# Stacking
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)

np.vstack((a,b))
np.hstack((a,b))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [40]:
# Spliting

a = np.arange(30).reshape(2,15)
print(a)

result = np.hsplit(a,3)
print(result)

for r in result:
    print(r)
    
result = np.vsplit(a,2)

for r in result:
    print(r)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [44]:
# Indexing with boolean array

a = np.arange(10).reshape(2,5)
print(a)

b = a>4
print(b)

print(a[b])

a[b] = 99
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[False False False False False]
 [ True  True  True  True  True]]
[5 6 7 8 9]
[[ 0  1  2  3  4]
 [99 99 99 99 99]]
