In [22]:
import numpy as np

In [23]:
x = np.arange(20, dtype=np.int32).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [24]:
np.savetxt("F:/Jay/Python/Code Basics Youtube/Numpy/test.txt",x)

In [25]:
y = np.loadtxt('F:/Jay/Python/Code Basics Youtube/Numpy/test.txt', dtype=np.int32 )
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
