In [25]:
import numpy as np

In [26]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
for i in np.nditer(a, order="C"):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
for i in np.nditer(a, order="F"):
    print(i)

1
5
9
2
6
10
3
7
11
4
8
12


In [29]:
for i in np.nditer(a,order="F", flags=["external_loop"]):
    print(i)

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [30]:
print(a)
for i in np.nditer(a, op_flags=['readwrite']):
    i[...] = i*i
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [37]:
b = np.arange(1,13,4).reshape(3,1)
print(b)

[[1]
 [5]
 [9]]


In [38]:
for i,j in np.nditer([a,b]):
    print(i,j)

1 1
4 1
9 1
16 1
25 5
36 5
49 5
64 5
81 9
100 9
121 9
144 9
