In [72]:
# Pickle and Joblib works in a similar way but Joblib is more efficient when having big data.
# It doesn't save numpy arrays or dataframes for data. It saves m's and b's generated by training datasets boz that is enough to predict.

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

import pickle
import joblib

In [62]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [63]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [64]:
reg.predict(np.array(3300).reshape(1,1))

array([628715.75342466])

In [65]:
print(reg.coef_)
print(reg.intercept_)
print('Predicted price is {}'.format(reg.predict(np.array([5000]).reshape(1,1))))

[135.78767123]
180616.43835616432
Predicted price is [859554.79452055]


In [66]:
# PICKLE

In [67]:
# Saving

with open('model_pickle','wb') as f: #wb is write binary
    pickle.dump(reg, f)

In [68]:
# Opening saved model

with open('model_pickle','rb') as f: #rb is read binary
    saved_model = pickle.load(f)
    
saved_model.predict(np.array([4000]).reshape(1,1))

array([723767.12328767])

In [69]:
# JOBLIB

In [70]:
# Saving 

joblib.dump(reg,'model_joblib')

['model_joblib']

In [71]:
# Loading

saved_joblib_model = joblib.load('model_joblib')
saved_joblib_model.predict(np.array([3500]).reshape(1,1))

array([655873.28767123])